services:
    app:
        build: .
        container_name: webpricer-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www:delegated
        networks:
            - laravel
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: webpricer-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www:delegated
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: mysql:8.4
        container_name: webpricer_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: radio_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: webpricer_admin
            MYSQL_PASSWORD: test123
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel
        deploy:
            resources:
                limits:
                    cpus: '6'
                    memory: 8G

    scheduler:
        build: .
        container_name: laravel_scheduler
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www:delegated
        command: ["php", "artisan", "schedule:work"]
        depends_on:
            - app
            - db
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
