version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "${APP_PORT:-8000}:80"
        networks:
            - laravel_network
        depends_on:
            - db

    db:
        image: mysql:8.4.2
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: web_pricer
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

    node:
        image: node:23 # если Node.js 23 недоступен, используйте node:20 или node:21
        container_name: laravel_node
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: sh -c "npm install && npm run dev"
        networks:
            - laravel_network
        depends_on:
            - app

volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge
