version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: radio-db/app
        container_name: webpricer-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - webpricer-network

    nginx:
        image: nginx:alpine
        container_name: webpricer-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/ssl/:/etc/nginx/ssl/
        networks:
            - webpricer-network

    db:
        image: mysql:8.0
        container_name: webpricer-db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: radio_db
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - webpricer-network

    node:
        image: node:20
        container_name: webpricer-node
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run dev"
        networks:
            - webpricer-network

networks:
    webpricer-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
