services:
    app:
        build: .
        container_name: app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: webpricer-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: mysql:8.4
        container_name: webpricer_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: radio_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: webpricer_admin
            MYSQL_PASSWORD: test123
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    scheduler:
        build: .
        container_name: laravel_scheduler
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: [ "php", "artisan", "schedule:work" ]
        depends_on:
            - app
            - db
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
